# Generated by Django 3.1 on 2020-08-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Current_Inventory',
            fields=[
                ('inventoryID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=11)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=11)),
                ('minimalSupply', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
    ]
