# Generated by Django 3.1 on 2020-08-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('current_inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Current_Inventory',
            new_name='CurrentInventory',
        ),
    ]
