# Generated by Django 3.1.1 on 2020-10-06 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('current_inventory', '0002_auto_20200815_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentinventory',
            old_name='minimalSupply',
            new_name='minimal_supply',
        ),
        migrations.RenameField(
            model_name='currentinventory',
            old_name='unitPrice',
            new_name='unit_price',
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('productionID', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=11)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='current_inventory.currentinventory')),
            ],
        ),
    ]
